<?php
// Export all databases to SQL files

$host = '127.0.0.1';
$username = 'root';
$password = '';
$exportDir = __DIR__ . '/database_exports/';

// Create export directory if it doesn't exist
if (!is_dir($exportDir)) {
    mkdir($exportDir, 0777, true);
}

try {
    // Connect to MySQL without selecting a database
    $pdo = new PDO("mysql:host=$host", $username, $password);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    
    // Get all databases
    $stmt = $pdo->query("SHOW DATABASES");
    $databases = $stmt->fetchAll(PDO::FETCH_COLUMN);
    
    // Exclude system databases
    $exclude = ['information_schema', 'mysql', 'performance_schema', 'phpmyadmin', 'sys'];
    $databases = array_diff($databases, $exclude);
    
    echo "Found " . count($databases) . " databases to export.\n\n";
    
    foreach ($databases as $dbName) {
        echo "Exporting database: $dbName ...\n";
        
        $exportFile = $exportDir . $dbName . '_' . date('Y-m-d_H-i-s') . '.sql';
        
        // Use mysqldump if available, otherwise use PHP fallback
        $mysqldumpPath = 'C:\\xampp\\mysql\\bin\\mysqldump.exe';
        if (file_exists($mysqldumpPath)) {
            $command = sprintf(
                '%s -h %s -u %s %s %s > "%s" 2>&1',
                escapeshellarg($mysqldumpPath),
                escapeshellarg($host),
                escapeshellarg($username),
                $password ? '-p' . escapeshellarg($password) : '',
                escapeshellarg($dbName),
                $exportFile
            );
            exec($command, $output, $returnCode);
            
            if ($returnCode === 0 && file_exists($exportFile) && filesize($exportFile) > 0) {
                echo "  ✓ Exported to: $exportFile (" . round(filesize($exportFile) / 1024, 2) . " KB)\n";
            } else {
                echo "  ✗ mysqldump failed, trying PHP fallback...\n";
                exportDatabasePHP($pdo, $dbName, $exportFile);
            }
        } else {
            // Use PHP fallback
            exportDatabasePHP($pdo, $dbName, $exportFile);
        }
    }
    
    echo "\n====================================\n";
    echo "Export completed!\n";
    echo "Files saved to: $exportDir\n";
    echo "====================================\n";
    
} catch (PDOException $e) {
    die("Database connection failed: " . $e->getMessage() . "\n");
}

/**
 * Export database using PHP (fallback method)
 */
function exportDatabasePHP($pdo, $dbName, $exportFile) {
    try {
        $pdo->exec("USE $dbName");
        
        $sql = "-- Database: $dbName\n";
        $sql .= "-- Export Date: " . date('Y-m-d H:i:s') . "\n";
        $sql .= "-- Generated by PHP Export Script\n\n";
        $sql .= "CREATE DATABASE IF NOT EXISTS `$dbName`;\n";
        $sql .= "USE `$dbName`;\n\n";
        
        // Get all tables
        $tables = $pdo->query("SHOW TABLES")->fetchAll(PDO::FETCH_COLUMN);
        
        foreach ($tables as $table) {
            // Get create table statement
            $createTable = $pdo->query("SHOW CREATE TABLE `$table`")->fetch(PDO::FETCH_ASSOC);
            $sql .= "\n-- Table structure for table `$table`\n";
            $sql .= "DROP TABLE IF EXISTS `$table`;\n";
            $sql .= $createTable['Create Table'] . ";\n\n";
            
            // Get table data
            $rows = $pdo->query("SELECT * FROM `$table`")->fetchAll(PDO::FETCH_ASSOC);
            
            if (count($rows) > 0) {
                $sql .= "-- Dumping data for table `$table`\n";
                
                // Get column names
                $columns = array_keys($rows[0]);
                $columnList = '`' . implode('`, `', $columns) . '`';
                
                foreach ($rows as $row) {
                    $values = [];
                    foreach ($row as $value) {
                        if ($value === null) {
                            $values[] = 'NULL';
                        } else {
                            $values[] = "'" . addslashes($value) . "'";
                        }
                    }
                    $valueList = implode(', ', $values);
                    $sql .= "INSERT INTO `$table` ($columnList) VALUES ($valueList);\n";
                }
                $sql .= "\n";
            }
        }
        
        file_put_contents($exportFile, $sql);
        echo "  ✓ Exported to: $exportFile (" . round(filesize($exportFile) / 1024, 2) . " KB)\n";
        
    } catch (PDOException $e) {
        echo "  ✗ Failed to export $dbName: " . $e->getMessage() . "\n";
    }
}
